### ISSUE TITLE
problem working in TYPO3 8.7

### ISSUE THREAD

**Issue by p380** [cyberhouse/t3ext-newsauthor#1]
I installed the module and added the code below to the template:
`<f:if condition="{newsItem.feAuthor}">
                <div>
                    <h3>User: {newsItem.feAuthor.username}</h3>
                    <p>{newsItem.feAuthor.firstName} {newsItem.feAuthor.lastName}</p>
                </div>
 </f:if>`

Does not display user information.

I have installed:
* TYPO3 8.7
* news 6.1.1

kind regards

**Comment by p380** [comment]
I checked and now works, I made a mistake in the fluid code
is it possible to extend news with custom module (table), is the same way?

regards

**Comment by georgringer** [comment]
yes
